name: Ubuntu Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        dir
        cmake -S . -B build
        cmake --build build
        ./build/main
