name: Ubuntu Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile & test
      run: |
        dir
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build
        ./build/test
        ls /home/runner/work/main-cpp/main-cpp/build/_deps/sdl-build
