name: Ubuntu Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install opengl
      run: |
        sudo apt-get update
        sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: compile & test
      run: |
        dir
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --target SDL2
        ls /home/runner/work/main-cpp/main-cpp/build/_deps/sdl-build
        cmake --build build --target test
        ./build/test
        cmake --build build --target main
        ./build/main
